package org.navalplanner.web.common;

import java.util.ConcurrentModificationException;

public interface IIntegrationEntityModel {

    void setCodeAutogenerated(boolean codeAutogenerated)
            throws ConcurrentModificationException;

}
