/*
 * This file is part of LibrePlan
 *
 * Copyright (C) 2009-2010 Fundación para o Fomento da Calidade Industrial e
 *                         Desenvolvemento Tecnolóxico de Galicia
 * Copyright (C) 2010-2011 Igalia, S.L.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.libreplan.web.costcategories;

import org.libreplan.business.common.exceptions.InstanceNotFoundException;
import org.libreplan.business.common.exceptions.ValidationException;
import org.libreplan.business.costcategories.entities.TypeOfWorkHours;
import org.libreplan.web.common.BaseCRUDController;
import org.libreplan.web.common.Level;
import org.libreplan.web.common.Util;
import org.libreplan.web.common.components.NewDataSortableGrid;
import org.zkoss.zk.ui.Component;
import org.zkoss.zk.ui.event.CheckEvent;
import org.zkoss.zk.ui.event.Event;
import org.zkoss.zkplus.spring.SpringUtil;
import org.zkoss.zul.Messagebox;

import java.util.ConcurrentModificationException;
import java.util.List;

import static org.libreplan.web.I18nHelper._t;

/**
 * Controller for CRUD actions over a {@link TypeOfWorkHours}
 *
 * @author Jacobo Aragunde Perez <jaragunde@igalia.com>
 * @author Cristina Alvarino Pereza <cristina.alvarino@comtecsf.es>
 */
@SuppressWarnings("serial")
public class TypeOfWorkHoursCRUDController extends BaseCRUDController<TypeOfWorkHours> {

    private ITypeOfWorkHoursModel typeOfWorkHoursModel;

    private NewDataSortableGrid listing;

    public TypeOfWorkHoursCRUDController(){
        typeOfWorkHoursModel = (ITypeOfWorkHoursModel) SpringUtil.getBean("typeOfWorkHoursModel");
    }

    @Override
    public void doAfterCompose(Component comp) throws Exception {
        super.doAfterCompose(comp);
        listing = (NewDataSortableGrid) listWindow.getFellowIfAny("listing");

        // BaseCRUDController.doAfterCompose() already calls showListWindow() (which reloads
        // listWindow's bindings), but that happens before AnnotateBinderInit's own later
        // page-level pass has created any binder at all, so it's a no-op. Redo it here, now that
        // the binder exists. Only listWindow is reloaded - editWindow's bindings reference
        // controller.typeOfWorkHours, which is still null at this point (only set up by
        // initCreate()/initEdit(), called later); showEditWindow() reloads editWindow's own
        // bindings once that has happened.
        Util.createBindingsFor(comp);
        Util.reloadBindings(listWindow);
    }

    /**
     * IntegrationEntity.isCodeAutogenerated() returns a boxed Boolean - ZK's BeanELResolver only
     * recognizes the "is"-prefix getter convention for properties declared as primitive boolean,
     * so binding directly to it throws PropertyNotFoundException. This thin wrapper (with matching
     * setter for @save) exposes a primitive boolean instead.
     */
    public boolean isTypeOfWorkHoursCodeAutogenerated() {
        return getTypeOfWorkHours().isCodeAutogenerated();
    }

    public void setTypeOfWorkHoursCodeAutogenerated(boolean codeAutogenerated) {
        getTypeOfWorkHours().setCodeAutogenerated(codeAutogenerated);
    }

    protected void save() throws ValidationException {
        typeOfWorkHoursModel.confirmSave();
    }

    public List<TypeOfWorkHours> getTypesOfWorkHours() {
        // The grid's "model" property is declared as org.zkoss.zul.ListModel - AnnotateBinder has
        // no automatic List->ListModel coercion, so returning a plain List here throws a
        // ClassCastException when the binder tries to load it.
        return new org.zkoss.zul.ListModelList<>(typeOfWorkHoursModel.getTypesOfWorkHours());
    }

    /**
     * The list's rows used to be declared with a ZUML "each" template (self="@{each=...}") - under
     * this app's AnnotateBinder/ZK 10 stack that only ever clones the row's FIRST child for each
     * iteration. Building rows programmatically via RowRenderer sidesteps that "each" bug entirely.
     */
    public org.zkoss.zul.RowRenderer getTypeOfWorkHoursRenderer() {
        return (row, data, index) -> {
            final TypeOfWorkHours typeOfWorkHours = (TypeOfWorkHours) data;
            row.setValue(typeOfWorkHours);
            row.addEventListener(org.zkoss.zk.ui.event.Events.ON_CLICK, event -> goToEditForm(typeOfWorkHours));

            row.appendChild(new org.zkoss.zul.Label(typeOfWorkHours.getCode()));
            row.appendChild(new org.zkoss.zul.Label(typeOfWorkHours.getName()));

            org.zkoss.zul.Hbox priceBox = new org.zkoss.zul.Hbox();
            priceBox.appendChild(new org.zkoss.zul.Label(
                    typeOfWorkHours.getDefaultPrice() != null ? typeOfWorkHours.getDefaultPrice().toString() : ""));
            priceBox.appendChild(new org.zkoss.zul.Label(getCurrencySymbol()));
            row.appendChild(priceBox);

            org.zkoss.zul.Checkbox enabled = new org.zkoss.zul.Checkbox();
            enabled.setChecked(typeOfWorkHours.getEnabled());
            enabled.setDisabled(true);
            row.appendChild(enabled);

            org.zkoss.zul.Hbox hbox = new org.zkoss.zul.Hbox();
            hbox.appendChild(Util.createEditButton(event -> goToEditForm(typeOfWorkHours)));
            hbox.appendChild(Util.createRemoveButton(event -> confirmDelete(typeOfWorkHours)));
            row.appendChild(hbox);
        };
    }

    public TypeOfWorkHours getTypeOfWorkHours() {
        return typeOfWorkHoursModel.getTypeOfWorkHours();
    }

    public void onCheckGenerateCode(Event e) {
        CheckEvent ce = (CheckEvent) e;
        if (ce.isChecked()) {
            try {
                // We have to auto-generate the code
                typeOfWorkHoursModel.setCodeAutogenerated(ce.isChecked());
            } catch (ConcurrentModificationException err) {
                messagesForUser.showMessage(Level.ERROR, err.getMessage());
            }
        }
        Util.reloadBindings(editWindow);
    }

    private boolean isReferencedByOtherEntities(TypeOfWorkHours typeOfWorkHours) {
        try {
            typeOfWorkHoursModel.checkIsReferencedByOtherEntities(typeOfWorkHours);
            return false;
        } catch (ValidationException e) {
            showCannotDeleteWorkHoursTypeDialog(e.getInvalidValue().getMessage());
        }
        return true;
    }

    private void showCannotDeleteWorkHoursTypeDialog(String message) {
        Messagebox.show(_t(message), _t("Warning"), Messagebox.OK, Messagebox.EXCLAMATION);
    }

    @Override
    protected String getEntityType() {
        return _t("Hours Type");
    }

    @Override
    protected String getPluralEntityType() {
        return _t("Hours Types");
    }

    @Override
    protected void initCreate() {
        typeOfWorkHoursModel.initCreate();
    }

    @Override
    protected void initEdit(TypeOfWorkHours typeOfWorkHours) {
        typeOfWorkHoursModel.initEdit(typeOfWorkHours);
    }

    @Override
    protected TypeOfWorkHours getEntityBeingEdited() {
        return typeOfWorkHoursModel.getTypeOfWorkHours();
    }

    @Override
    protected void delete(TypeOfWorkHours typeOfWorkHours) throws InstanceNotFoundException {
        typeOfWorkHoursModel.confirmRemove(typeOfWorkHours);
    }

    protected boolean beforeDeleting(TypeOfWorkHours typeOfWorkHours) {
        return !isReferencedByOtherEntities(typeOfWorkHours);
    }

    public String getCurrencySymbol() {
        return Util.getCurrencySymbol();
    }

    public String getMoneyFormat() {
        return Util.getMoneyFormat();
    }

}
