/*
 * This file is part of LibrePlan
 *
 * Copyright (C) 2009-2010 Fundación para o Fomento da Calidade Industrial e
 *                         Desenvolvemento Tecnolóxico de Galicia
 * Copyright (C) 2010-2011 Igalia, S.L.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.libreplan.business.calendars.entities;

import org.libreplan.business.calendars.daos.ICalendarExceptionTypeDAO;
import org.libreplan.business.common.daos.IEntitySequenceDAO;
import org.libreplan.business.common.entities.EntityNameEnum;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Creates the default {@link CalendarExceptionType}.
 *
 * @author Manuel Rego Casasnovas <mrego@igalia.com>
 */
@Component
@Scope("singleton")
public class CalendarBootstrap implements ICalendarBootstrap {

    @Autowired
    private ICalendarExceptionTypeDAO calendarExceptionTypeDAO;

    @Autowired
    private IEntitySequenceDAO entitySequenceDAO;

    @Override
    @Transactional
    public void loadRequiredData() {
        if (calendarExceptionTypeDAO.getAll().size() == 0) {
            for (PredefinedCalendarExceptionTypes type : PredefinedCalendarExceptionTypes
                    .values()) {
                CalendarExceptionType calendarExceptionType = type
                        .getCalendarExceptionType();
                calendarExceptionType
                        .setCode(entitySequenceDAO
                                .getNextEntityCodeWithoutTransaction(EntityNameEnum.CALENDAR_EXCEPTION_TYPE));
                calendarExceptionType.setCodeAutogenerated(true);
                calendarExceptionTypeDAO.save(calendarExceptionType);
            }
        }
        if (!calendarExceptionTypeDAO.getAll().contains(
                PredefinedCalendarExceptionTypes.NOT_WORKING_DAY
                        .getCalendarExceptionType())) {
            CalendarExceptionType calendarExceptionType = PredefinedCalendarExceptionTypes.NOT_WORKING_DAY
                    .getCalendarExceptionType();
            calendarExceptionType
                    .setCode(entitySequenceDAO
                            .getNextEntityCodeWithoutTransaction(EntityNameEnum.CALENDAR_EXCEPTION_TYPE));
            calendarExceptionType.setCodeAutogenerated(true);
            calendarExceptionTypeDAO.save(calendarExceptionType);
        }
        if (!calendarExceptionTypeDAO.getAll().contains(
                PredefinedCalendarExceptionTypes.WORKING_DAY
                        .getCalendarExceptionType())) {
            CalendarExceptionType calendarExceptionType = PredefinedCalendarExceptionTypes.WORKING_DAY
                    .getCalendarExceptionType();
            calendarExceptionType
                    .setCode(entitySequenceDAO
                            .getNextEntityCodeWithoutTransaction(EntityNameEnum.CALENDAR_EXCEPTION_TYPE));
            calendarExceptionType.setCodeAutogenerated(true);
            calendarExceptionTypeDAO.save(calendarExceptionType);
        }
    }

}
